import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paulo Duarte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Paulo Guilherme Pilotti Duarte
        </h1>

        <p>guilhermepilotti@gmail.com</p>

        <div className={styles.grid}>
          <a href="https://paulogpd.substack.com" className={styles.card}>
            <h2>Blog &rarr;</h2>
            <p>Blog no Substack, feito por mim com nenhum critério.</p>
          </a>

          <a href="https://paulogpd.notion.site/Curr-culo-6eafc66cc9cd4b89a75a1f921fd5cf57" className={styles.card}>
            <h2>Portfólio &rarr;</h2>
            <p>Um currículo completo, com portfólio do que eu fiz até hoje.</p>
          </a>

          <a
            href="https://github.com/mtgr18977"
            className={styles.card}
          >
            <h2>GitHub pessoal &rarr;</h2>
            <p>Códigos variados de cursos de Java, Python e da minha Pós.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Ensaios &rarr;</h2>
            <p>
              Ensaios variados. Escritos principalmente na época de universidade.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
